(() => {
  const imageBank = {
    "cat-all": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Bougainvillea_closeup.jpg",
    "cat-indoor": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Zamioculcas_zamiifolia_1.jpg",
    "cat-outdoor": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Hibiscus_flower_TZ.jpg",
    "cat-flower": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Rosa_rubiginosa_1.jpg",
    "cat-fruit": "https://upload.wikimedia.org/wikipedia/commons/3/32/Papaya_tree_DRC.jpg",
    "cat-decor": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Chamaedorea_elegans_02.jpg",
    "cat-pot": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Terracotta_pots_%2854588497997%29.jpg",
    b1: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Bougainvillea_closeup.jpg",
    b2: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Hibiscus_flower_TZ.jpg",
    c1: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Cactus_de_no%C3%ABl_rev.jpg",
    c2: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Cactus_de_no%C3%ABl_rev.jpg",
    z1: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Zamioculcas_zamiifolia_1.jpg",
    z2: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Zamioculcas_zamiifolia_1.jpg",
    rz1: "https://upload.wikimedia.org/wikipedia/commons/d/de/Raven_ZZ_Zamioculcas_Dowon_1.jpg",
    rz2: "https://upload.wikimedia.org/wikipedia/commons/d/de/Raven_ZZ_Zamioculcas_Dowon_1.jpg",
    g1: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Pelargonium_zonale_umbel.jpg",
    g2: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Pelargonium_colors.jpg",
    r1: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Rosa_rubiginosa_1.jpg",
    r2: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Rosa_rubiginosa_1.jpg",
    ci1: "https://upload.wikimedia.org/wikipedia/commons/d/da/Red_Cineraria_Pericallis_2.jpg",
    ci2: "https://upload.wikimedia.org/wikipedia/commons/d/da/Red_Cineraria_Pericallis_2.jpg",
    cp1: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Chamaedorea_elegans_02.jpg",
    cp2: "https://upload.wikimedia.org/wikipedia/commons/6/64/Chamaedorea_elegans_Mart.JPG",
    hp1: "https://upload.wikimedia.org/wikipedia/commons/3/32/Papaya_tree_DRC.jpg",
    hp2: "https://upload.wikimedia.org/wikipedia/commons/3/32/Papaya_tree_DRC.jpg",
    ap1: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Dypsis_lutescens1.jpg",
    ap2: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Dypsis_lutescens2.jpg",
    s1: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg",
    s2: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Snake_Plant_%28Sansevieria_trifasciata_%27Laurentii%27%29.jpg",
    m1: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Epipremnum_aureum_%28Marble_Queen%29_houseplant_%28cropped%29.png",
    m2: "https://upload.wikimedia.org/wikipedia/commons/b/b7/Epipremnum_aureum_%28Marble_Queen%29_houseplant_%28cropped%29.png",
    p1: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Terracotta_pots_%2854588497997%29.jpg",
    gs1: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Pebbles_garden_%2850109634871%29.jpg",
    gs2: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Decorative_stone.jpg",
    h1: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Hibiscus_flower_TZ.jpg",
    j1: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Crassula_ovata_700.jpg",
  };

  const products = [
    {
      id: "P-101",
      slug: "bougainvillea-premium-pink",
      name: "Bougainvillea Premium Pink",
      categoryKey: "flowering",
      category: "Flowering Plants",
      price: 950,
      stock: 14,
      popularity: 98,
      newestRank: 6,
      tag: "Best seller",
      badge: "Featured",
      featured: true,
      short: "Bright climbing color for gates and terraces.",
      long: "A vigorous bougainvillea chosen for boundary walls, entrance gates, and sunny terraces where long-lasting color matters.",
      care: { sunlight: "Full sun", watering: "2 to 3 times weekly", maintenance: "Moderate", growth: "Climbing shrub" },
      delivery: "Available for local delivery or nursery pickup.",
      images: ["b1", "b2", "cat-outdoor"],
    },
    {
      id: "P-102",
      slug: "christmas-cactus-bloom",
      name: "Christmas Cactus Bloom",
      categoryKey: "indoor",
      category: "Indoor Plants",
      price: 780,
      stock: 11,
      popularity: 86,
      newestRank: 8,
      tag: "Season favorite",
      badge: "Seasonal",
      featured: true,
      short: "Compact indoor bloomer for tables and windows.",
      long: "A festive flowering cactus that suits bright corners, study tables, and sheltered windows without demanding daily attention.",
      care: { sunlight: "Bright indirect light", watering: "When top soil dries", maintenance: "Easy", growth: "Compact succulent" },
      delivery: "Packed carefully for short-distance delivery.",
      images: ["c1", "c2", "cat-indoor"],
    },
    {
      id: "P-103",
      slug: "zz-plant-green",
      name: "ZZ Plant Green",
      categoryKey: "indoor",
      category: "Indoor Plants",
      price: 1250,
      stock: 19,
      popularity: 96,
      newestRank: 7,
      tag: "Low maintenance",
      badge: "Popular",
      featured: true,
      short: "Reliable glossy foliage for homes and offices.",
      long: "A dependable indoor plant for living rooms, office desks, and reception corners where customers want a clean, premium look with less watering.",
      care: { sunlight: "Low to bright indirect light", watering: "Every 7 to 10 days", maintenance: "Very easy", growth: "Upright clumping plant" },
      delivery: "Delivered potted and ready to place indoors.",
      images: ["z1", "z2", "cat-indoor"],
    },
    {
      id: "P-104",
      slug: "zz-plant-black-raven",
      name: "ZZ Plant Black Raven",
      categoryKey: "decorative",
      category: "Decorative Plants",
      price: 1650,
      stock: 8,
      popularity: 83,
      newestRank: 10,
      tag: "Premium indoor look",
      badge: "New",
      featured: false,
      short: "A darker ZZ variety for stylish corners.",
      long: "Black Raven ZZ adds depth and contrast to modern interiors, premium pots, and polished business spaces.",
      care: { sunlight: "Low to medium light", watering: "Every 8 to 12 days", maintenance: "Easy", growth: "Compact upright grower" },
      delivery: "Short-distance delivery available with extra wrapping.",
      images: ["rz1", "rz2", "cat-decor"],
    },
    {
      id: "P-105",
      slug: "geranium-scarlet",
      name: "Geranium Scarlet",
      categoryKey: "flowering",
      category: "Flowering Plants",
      price: 620,
      stock: 22,
      popularity: 88,
      newestRank: 4,
      tag: "Long blooming",
      badge: "Hot pick",
      featured: true,
      short: "Colorful flowering plant for sunny verandas.",
      long: "A cheerful geranium variety for balcony rails, front steps, and verandas that need dependable color through the season.",
      care: { sunlight: "Morning sun to full sun", watering: "Keep lightly moist", maintenance: "Easy to moderate", growth: "Bushy flowering plant" },
      delivery: "Best delivered with bloom support packaging.",
      images: ["g1", "g2", "cat-flower"],
    },
    {
      id: "P-106",
      slug: "rose-plant-hybrid-red",
      name: "Rose Plant Hybrid Red",
      categoryKey: "flowering",
      category: "Flowering Plants",
      price: 890,
      stock: 16,
      popularity: 92,
      newestRank: 5,
      tag: "Customer favorite",
      badge: "Featured",
      featured: true,
      short: "Healthy hybrid rose with classic garden charm.",
      long: "A trusted rose plant for home gardens, gifting, and courtyard planting where customers want familiar beauty and fragrance.",
      care: { sunlight: "Full sun", watering: "Every 2 to 3 days", maintenance: "Moderate", growth: "Shrub rose" },
      delivery: "Fresh rose stock is packed upright for safe transport.",
      images: ["r1", "r2", "cat-flower"],
    },
    {
      id: "P-107",
      slug: "cineraria-winter-mix",
      name: "Cineraria Winter Mix",
      categoryKey: "flowering",
      category: "Flowering Plants",
      price: 540,
      stock: 25,
      popularity: 76,
      newestRank: 9,
      tag: "Seasonal bloom",
      badge: "Seasonal",
      featured: false,
      short: "Cool-season color for festive corners.",
      long: "A popular seasonal bloomer for events, porches, and gift-ready corners where soft color makes a quick impact.",
      care: { sunlight: "Bright filtered light", watering: "Keep evenly moist", maintenance: "Moderate", growth: "Compact seasonal bloomer" },
      delivery: "Seasonal stock changes quickly, so early orders are recommended.",
      images: ["ci1", "ci2", "cat-flower"],
    },
    {
      id: "P-108",
      slug: "charmonda-palm",
      name: "Charmonda Palm",
      categoryKey: "decorative",
      category: "Decorative Plants",
      price: 2100,
      stock: 9,
      popularity: 81,
      newestRank: 11,
      tag: "Entrance statement",
      badge: "Premium",
      featured: true,
      short: "Elegant decorative palm for polished spaces.",
      long: "A decorative palm suited to entrances, living rooms, hospitality counters, and styled corners that need height and freshness.",
      care: { sunlight: "Bright indirect to gentle sun", watering: "2 times weekly", maintenance: "Moderate", growth: "Upright palm form" },
      delivery: "Delivery available with upright handling for larger specimens.",
      images: ["cp1", "cp2", "cat-decor"],
    },
    {
      id: "P-109",
      slug: "hybrid-papaya-plant",
      name: "Hybrid Papaya Plant",
      categoryKey: "fruit",
      category: "Fruit Plants",
      price: 520,
      stock: 31,
      popularity: 90,
      newestRank: 3,
      tag: "Fast-growing",
      badge: "Top value",
      featured: true,
      short: "Healthy fruit plant for kitchen gardens.",
      long: "A practical papaya plant for customers building productive home gardens with quick establishment and good value.",
      care: { sunlight: "Full sun", watering: "Regular deep watering", maintenance: "Moderate", growth: "Fast-growing fruit plant" },
      delivery: "Best planted soon after pickup or delivery.",
      images: ["hp1", "hp2", "cat-fruit"],
    },
    {
      id: "P-110",
      slug: "areca-palm-indoor",
      name: "Areca Palm Indoor",
      categoryKey: "indoor",
      category: "Indoor Plants",
      price: 1950,
      stock: 12,
      popularity: 84,
      newestRank: 12,
      tag: "Air purifying",
      badge: "Premium",
      featured: false,
      short: "Lush indoor palm for living rooms and offices.",
      long: "The Areca Palm softens interiors beautifully and works especially well in larger rooms, office corners, and balcony seating areas.",
      care: { sunlight: "Bright indirect light", watering: "2 to 3 times weekly", maintenance: "Moderate", growth: "Feathery indoor palm" },
      delivery: "Available with styling support on request.",
      images: ["ap1", "ap2", "cat-indoor"],
    },
    {
      id: "P-111",
      slug: "snake-plant-sansevieria",
      name: "Snake Plant Sansevieria",
      categoryKey: "indoor",
      category: "Indoor Plants",
      price: 890,
      stock: 27,
      popularity: 94,
      newestRank: 2,
      tag: "Air purifying",
      badge: "Popular",
      featured: true,
      short: "Tough upright plant for bedrooms and desks.",
      long: "A trusted low-maintenance plant for bedrooms, study tables, and office desks where easy care matters most.",
      care: { sunlight: "Low to bright indirect light", watering: "Every 10 to 14 days", maintenance: "Very easy", growth: "Architectural upright leaves" },
      delivery: "Available in nursery pot or styled pot options.",
      images: ["s1", "s2", "cat-indoor"],
    },
    {
      id: "P-112",
      slug: "money-plant-marble-queen",
      name: "Money Plant Marble Queen",
      categoryKey: "decorative",
      category: "Decorative Plants",
      price: 650,
      stock: 24,
      popularity: 79,
      newestRank: 1,
      tag: "Easy trailing plant",
      badge: "New",
      featured: false,
      short: "Variegated money plant for shelves and hangers.",
      long: "A decorative trailing money plant that lifts shelves, stair landings, and hanging spots with a lighter variegated look.",
      care: { sunlight: "Medium to bright indirect light", watering: "Once or twice weekly", maintenance: "Easy", growth: "Trailing vine" },
      delivery: "Prepared for transport with secure trailing support.",
      images: ["m1", "m2", "cat-decor"],
    },
    {
      id: "P-113",
      slug: "decorative-terracotta-pot-set",
      name: "Decorative Terracotta Pot Set",
      categoryKey: "accessories",
      category: "Pots & Garden Accessories",
      price: 1450,
      stock: 18,
      popularity: 74,
      newestRank: 13,
      tag: "Complete setup",
      badge: "Bundle",
      featured: false,
      short: "Three-piece terracotta pot set.",
      long: "A warm earthy pot set for verandas, balconies, and front steps where customers want a finished planted look.",
      care: { sunlight: "Indoor or outdoor use", watering: "Drainage holes included", maintenance: "Easy care accessory", growth: "Supports many plant types" },
      delivery: "Pot sets are wrapped securely for safe transport.",
      images: ["p1", "cat-pot", "cat-all"],
    },
    {
      id: "P-114",
      slug: "polished-garden-stones",
      name: "Polished Garden Stones",
      categoryKey: "accessories",
      category: "Pots & Garden Accessories",
      price: 380,
      stock: 40,
      popularity: 68,
      newestRank: 14,
      tag: "Landscape finishing",
      badge: "Add-on",
      featured: false,
      short: "Decorative stones for planters and pathways.",
      long: "Useful for planter topping, edging, small garden paths, and cleaner display finishes around potted plants.",
      care: { sunlight: "Suitable for all placements", watering: "Use as planter topping or border stone", maintenance: "No-maintenance accessory", growth: "Supports visual presentation" },
      delivery: "Available by pack, with larger quantity pricing on request.",
      images: ["gs1", "gs2", "cat-pot"],
    },
    {
      id: "P-115",
      slug: "hibiscus-sunshine-yellow",
      name: "Hibiscus Sunshine Yellow",
      categoryKey: "outdoor",
      category: "Outdoor Plants",
      price: 720,
      stock: 17,
      popularity: 82,
      newestRank: 15,
      tag: "Garden color",
      badge: "Featured",
      featured: true,
      short: "Bold yellow outdoor bloomer.",
      long: "A bright hibiscus for front yards, sunny compound edges, and courtyards that need strong seasonal color.",
      care: { sunlight: "Full sun", watering: "Regular watering in dry weather", maintenance: "Moderate", growth: "Flowering shrub" },
      delivery: "Delivered in nursery bag or upgraded pot on request.",
      images: ["h1", "cat-outdoor", "cat-flower"],
    },
    {
      id: "P-116",
      slug: "jade-plant-classic",
      name: "Jade Plant Classic",
      categoryKey: "decorative",
      category: "Decorative Plants",
      price: 560,
      stock: 21,
      popularity: 72,
      newestRank: 16,
      tag: "Gift-friendly",
      badge: "Easy care",
      featured: false,
      short: "Compact succulent with a clean sturdy look.",
      long: "A neat decorative succulent for desks, study corners, and gift arrangements where tidy form matters more than fuss.",
      care: { sunlight: "Bright light", watering: "When soil fully dries", maintenance: "Very easy", growth: "Compact succulent shrub" },
      delivery: "Packed carefully to protect stems and leaves.",
      images: ["j1", "cat-decor", "cat-pot"],
    },
  ];

  const resolveImages = (keys) => keys.map((key) => imageBank[key] || imageBank["cat-all"]);
  const withResolvedImages = products.map((product) => ({
    ...product,
    image: imageBank[product.images[0]],
    gallery: resolveImages(product.images),
  }));

  const api = Object.assign(window.NurseryData, {
    productImages: imageBank,
    products: withResolvedImages,
    getProductBySlug(slug) {
      return withResolvedImages.find((product) => product.slug === slug);
    },
    getProductById(id) {
      return withResolvedImages.find((product) => product.id === id);
    },
    getFeaturedProducts(limit) {
      const list = withResolvedImages.filter((product) => product.featured);
      return typeof limit === "number" ? list.slice(0, limit) : list;
    },
    getRelatedProducts(product, limit) {
      if (!product) return [];
      const sameCategory = withResolvedImages.filter(
        (item) => item.id !== product.id && item.categoryKey === product.categoryKey
      );
      const fallback = withResolvedImages.filter((item) => item.id !== product.id);
      return sameCategory.concat(fallback).slice(0, limit || 4);
    },
    getCategoryByKey(key) {
      return this.categories.find((category) => category.key === key) || this.categories[0];
    },
  });

  window.NurseryData = api;
})();
